# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import food_ordering_pb2 as food__ordering__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in food_ordering_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FoodOrderingServiceStub:
    """============================================================
    Food Ordering Service
    Section 3 - Problem 2 (Team 32)
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRestaurants = channel.unary_unary(
                '/foodordering.FoodOrderingService/ListRestaurants',
                request_serializer=food__ordering__pb2.Empty.SerializeToString,
                response_deserializer=food__ordering__pb2.RestaurantResponse.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/foodordering.FoodOrderingService/PlaceOrder',
                request_serializer=food__ordering__pb2.OrderRequest.SerializeToString,
                response_deserializer=food__ordering__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/foodordering.FoodOrderingService/GetOrderStatus',
                request_serializer=food__ordering__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=food__ordering__pb2.OrderStatusResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/foodordering.FoodOrderingService/CancelOrder',
                request_serializer=food__ordering__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=food__ordering__pb2.Acknowledge.FromString,
                _registered_method=True)
        self.ViewPendingOrders = channel.unary_unary(
                '/foodordering.FoodOrderingService/ViewPendingOrders',
                request_serializer=food__ordering__pb2.RestaurantNameRequest.SerializeToString,
                response_deserializer=food__ordering__pb2.PendingOrdersResponse.FromString,
                _registered_method=True)
        self.UpdateOrderStatus = channel.unary_unary(
                '/foodordering.FoodOrderingService/UpdateOrderStatus',
                request_serializer=food__ordering__pb2.OrderStatusUpdate.SerializeToString,
                response_deserializer=food__ordering__pb2.Acknowledge.FromString,
                _registered_method=True)
        self.SubscribeToOrderUpdates = channel.unary_stream(
                '/foodordering.FoodOrderingService/SubscribeToOrderUpdates',
                request_serializer=food__ordering__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=food__ordering__pb2.OrderUpdate.FromString,
                _registered_method=True)


class FoodOrderingServiceServicer:
    """============================================================
    Food Ordering Service
    Section 3 - Problem 2 (Team 32)
    ============================================================
    """

    def ListRestaurants(self, request, context):
        """Returns the predefined list of restaurants and their menus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Places a new order for a customer at a given restaurant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Returns the current status/details of a single order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancels an order. Only allowed while the order is still PLACED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewPendingOrders(self, request, context):
        """Restaurant-side: view all orders currently pending at a restaurant
        (i.e. not yet in a terminal state: READY or CANCELLED).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrderStatus(self, request, context):
        """Restaurant-side: advance an order's status.
        Only the owning restaurant may update its own orders.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToOrderUpdates(self, request, context):
        """Customer-side: server-streaming subscription. The server pushes an
        OrderUpdate every time the given order's status changes, and closes
        the stream once the order reaches a terminal state (READY/CANCELLED).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FoodOrderingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRestaurants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRestaurants,
                    request_deserializer=food__ordering__pb2.Empty.FromString,
                    response_serializer=food__ordering__pb2.RestaurantResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=food__ordering__pb2.OrderRequest.FromString,
                    response_serializer=food__ordering__pb2.OrderResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=food__ordering__pb2.OrderIdRequest.FromString,
                    response_serializer=food__ordering__pb2.OrderStatusResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=food__ordering__pb2.OrderIdRequest.FromString,
                    response_serializer=food__ordering__pb2.Acknowledge.SerializeToString,
            ),
            'ViewPendingOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewPendingOrders,
                    request_deserializer=food__ordering__pb2.RestaurantNameRequest.FromString,
                    response_serializer=food__ordering__pb2.PendingOrdersResponse.SerializeToString,
            ),
            'UpdateOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrderStatus,
                    request_deserializer=food__ordering__pb2.OrderStatusUpdate.FromString,
                    response_serializer=food__ordering__pb2.Acknowledge.SerializeToString,
            ),
            'SubscribeToOrderUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToOrderUpdates,
                    request_deserializer=food__ordering__pb2.OrderIdRequest.FromString,
                    response_serializer=food__ordering__pb2.OrderUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foodordering.FoodOrderingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('foodordering.FoodOrderingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FoodOrderingService:
    """============================================================
    Food Ordering Service
    Section 3 - Problem 2 (Team 32)
    ============================================================
    """

    @staticmethod
    def ListRestaurants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foodordering.FoodOrderingService/ListRestaurants',
            food__ordering__pb2.Empty.SerializeToString,
            food__ordering__pb2.RestaurantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foodordering.FoodOrderingService/PlaceOrder',
            food__ordering__pb2.OrderRequest.SerializeToString,
            food__ordering__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foodordering.FoodOrderingService/GetOrderStatus',
            food__ordering__pb2.OrderIdRequest.SerializeToString,
            food__ordering__pb2.OrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foodordering.FoodOrderingService/CancelOrder',
            food__ordering__pb2.OrderIdRequest.SerializeToString,
            food__ordering__pb2.Acknowledge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewPendingOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foodordering.FoodOrderingService/ViewPendingOrders',
            food__ordering__pb2.RestaurantNameRequest.SerializeToString,
            food__ordering__pb2.PendingOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foodordering.FoodOrderingService/UpdateOrderStatus',
            food__ordering__pb2.OrderStatusUpdate.SerializeToString,
            food__ordering__pb2.Acknowledge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToOrderUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/foodordering.FoodOrderingService/SubscribeToOrderUpdates',
            food__ordering__pb2.OrderIdRequest.SerializeToString,
            food__ordering__pb2.OrderUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
