# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import log_analytics_pb2 as log__analytics__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in log_analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogAnalyticsServiceStub:
    """============================================================
    Real-Time Server Log Analytics over gRPC
    Section 2 - Q2 (Team 32)
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamLogs = channel.stream_unary(
                '/loganalytics.LogAnalyticsService/StreamLogs',
                request_serializer=log__analytics__pb2.LogRecord.SerializeToString,
                response_deserializer=log__analytics__pb2.IngestSummary.FromString,
                _registered_method=True)
        self.GetAnalytics = channel.unary_unary(
                '/loganalytics.LogAnalyticsService/GetAnalytics',
                request_serializer=log__analytics__pb2.Empty.SerializeToString,
                response_deserializer=log__analytics__pb2.AnalyticsSnapshot.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/loganalytics.LogAnalyticsService/Reset',
                request_serializer=log__analytics__pb2.Empty.SerializeToString,
                response_deserializer=log__analytics__pb2.Ack.FromString,
                _registered_method=True)


class LogAnalyticsServiceServicer:
    """============================================================
    Real-Time Server Log Analytics over gRPC
    Section 2 - Q2 (Team 32)
    ============================================================
    """

    def StreamLogs(self, request_iterator, context):
        """Client-streaming ingestion: the streaming client sends one LogRecord per
        request, replaying a pre-generated dataset as if it were a live feed.
        The server returns a single summary once the client closes the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalytics(self, request, context):
        """Query the current (possibly still-ingesting) analytics snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Clears all accumulated state (used between correctness test runs).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogAnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=log__analytics__pb2.LogRecord.FromString,
                    response_serializer=log__analytics__pb2.IngestSummary.SerializeToString,
            ),
            'GetAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalytics,
                    request_deserializer=log__analytics__pb2.Empty.FromString,
                    response_serializer=log__analytics__pb2.AnalyticsSnapshot.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=log__analytics__pb2.Empty.FromString,
                    response_serializer=log__analytics__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loganalytics.LogAnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loganalytics.LogAnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogAnalyticsService:
    """============================================================
    Real-Time Server Log Analytics over gRPC
    Section 2 - Q2 (Team 32)
    ============================================================
    """

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/loganalytics.LogAnalyticsService/StreamLogs',
            log__analytics__pb2.LogRecord.SerializeToString,
            log__analytics__pb2.IngestSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loganalytics.LogAnalyticsService/GetAnalytics',
            log__analytics__pb2.Empty.SerializeToString,
            log__analytics__pb2.AnalyticsSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loganalytics.LogAnalyticsService/Reset',
            log__analytics__pb2.Empty.SerializeToString,
            log__analytics__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
